### PR TITLE
AmqpSettings.IdleTimeout int to uint

### PR DESCRIPTION
**Pull request by optimuserik**
Change the default AmqpSettings.IdleTimeout from int to uint.
Chenge the initialization from int.MaxValue to uint.MaxValue

### CODE REVIEW

**Review by optimuserik — COMMENTED** [review]
@microsoft-github-policy-service agree

**Comment by optimuserik** [comment]
@microsoft-github-policy-service agree

**Comment by optimuserik** [comment]
@microsoft-github-policy-service agree

**Comment by optimuserik** [comment]
@microsoft-github-policy-service rerun

**Comment by xinchen10** [comment]
Unfortunately this is a breaking change which we are trying to avoid as much as possible.

Let me check the feasibility of still using an int type but allowing negative values, with "-1" being the special case for infinite (no timeout).

**Comment by xinchen10** [comment]
@optimuserik I made a change to allow using -1 for infinite idle timeout. Can you verify if that resolves the issue you observed?

**Comment by optimuserik** [comment]
@xinchen10 It does solve the issue. Thank you :) .
I will abandon this PR and mark the problem solved with your commit. 
Awaiting the release.

**Pull request closed without merging**
