### PR TITLE
Implement compile option for small memory devices

### PR DESCRIPTION
**Pull request by josesimoes**
- Rework code to reduce memory and flash footprint to make this library
usefull in resource constrained devices with small memory.
- Add option for less verbose exceptions and error messages.
- Add option to remove trace.
- Change several method declarations to receive arguments as ref instead
of copying them in memory over and over (which is overkilling when RAM
is scarce).

To use this just add SMALL_MEMORY to project compilation symbols and
(VERY IMPORTANT) reload the project.

### CODE REVIEW

**Comment by xinchen10** [comment]
Thank you very much for the contribution. Here are some general comments about the changes.
1. The current code use the TRACE symbol to control ToString method of classes under types and framing namespaces. I'd like to use it for other tracing/diagnostics related code, so we don't have to introduce SMALL_MEMORY.
2. Overall I want to reduce the amount of conditional code based on SMALL_MEMORY. Here are a few strategies I can think of.
(1) Instead of not calling a method, we can always call it but if the symbol is defined, have an empty method body in the implementation. I think the method will be removed with compiler's optimization.
(2) Use ConditionalAttribute on methods if possible and they will be removed by compiler if symbol is not defined.
It seems that the passing-by-reference change to the ByteBuffer parameter is leading to significant amount of code changes and duplication which is not ideal for maintaining the code base. I suggest we separate the trace changes from the parameter passing changes so the issues can be addressed separately and at different times.

Regards,
Xin

**Comment by josesimoes** [comment]
Hi Xin,

Thank you for reviewing this. Need you to clarify a couple of things please:

1. Are you saying that we would be better using the TRACE directive instead of SMALL_MEMORY?

2. (1) I can't remember "not" calling a method. Instead I've changed the declaration of several ones to include the ref in arguments. So I'm not following your suggestion to have empty methods...
(2) I'm afraid I'm not following your suggestion on using the ConditionalAttribute... If understand that that attribute marks methods to the included in compilation (or not). I can't use that to "change" a method declaration, can I? I'm not aware of an attribute that does that.

Could you please implement your suggestions on a couple of methods and I'll follow?
Also I gave it some more thought and I believe that having a separate project file for this "small memory" variant would be better instead of using the "CHOOSE" in the project file. What do you think about this? (are you OK with naming it Amqp.SmallMemory.NetMF43 or do you have a better idea?)

Looking forward to your answers/feedback. :smile:

**Comment by xinchen10** [comment]
1. Yes, but only for the resource string and exception message parts.
2. I was thinking that we should break this change into two: one for reducing tracing/exceptions overhead and another for the ByteBuffer parameter change. My suggestions are about the first. For the second I am not sure if it is justified given the amount of code change/duplication and other (possibly better?) solutions for solving the memory constraint issue (see below). Supporting NETMF is important but at the same time the code is shared by all other platforms.

On NETMF devices things are different. Typically the app is using only some part of the library and once it is deployed it seldom changes. Having the full library is a waste of space and memory. Unfortunately there is no static linking to get only what you need into the application. I was thinking that we could introduce a special version which only does simple send/receive by encoding/decoding frames from the connection. There is no multiplexing of sessions/links. You simply call TinySender.Send(message) and internally it encodes everything into a buffer and writes it to the transport directly. With this approach we can eliminate a lot of code. If someone needs more features they can go with the full Amqp.NetMF version. Does that sound reasonable?

**Comment by josesimoes** [comment]
Hi Xin,

Understood and I'm OK with 1.

I totally agree with your assessment on the NETMF constrains (both platform and compiling options). Having a special version for NETMF that removes code and reduces RAM requirements would be the ideal approach.
For 99% of the apps running on NETMF devices for sure there won't be any need for session/link multiplexing. As you put it: if someone needs the full features he/she can use the full NETMF version.

I don't want to break the library design and for sure you have a better understanding of the global picture. Would you care to put in place a "skeleton" version for the tiny version? After you do that I can take over and fill in the code.

Does this work for you?

**Comment by josesimoes** [comment]
Hi Xin,

Just commit several changes that implement your suggestion on using TRACE instead of SMALL_MEMORY to improve the exceptions and actual trace code. 
Please review it and let me know if that is inline with what you've suggested.

Any thoughts on how to proceed with the "tiny" version of the library?

**Comment by xinchen10** [comment]
Hi,
I will take a look at the changes. For the tiny version I thought we should define the user interfaces first and then take the minimal code (e.g. transport, codec) that can be reused to implement it. We may also need to write new code but that's ok. For user interfaces I don't think we need the connection/session/link model. It might be as simple as a Sender class with a Send(Message) method. I will create a new project and start experimenting with it.

**Comment by josesimoes** [comment]
Hi Xin,

I agree with your suggested implementation except for some of the simplification. I'm thinking on some use scenarios such as Azure IoT Hub where it could be beneficial to be able to reuse sessions (because of the authentication and such) when implementing a send/receive app. Being able to have a listener for incoming messages, instead of having to pull then, is also something to be considered.
Let me know what I can do as soon as you have all this figured out.

**Comment by xinchen10** [comment]
Hi, I have been doing some experiments with this tiny version of the library. I got something to work and put the code up to the netmf-tiny branch. There are four main classes: Client, Sender, Receiver and Message. The client internally manages one connection and one session. It supports two links for Sender and Receiver (maybe at different addresses) respectively. The PE file size is reduced to 24KB (from 62KB). The new sample (Device.SmallMemory) shows how to use it. There are a few things remaining (e.g. error handling, code cleanup, etc) but it should be working in most cases. Feedback is very welcome.
Hi, I have been doing some experiments with this tiny version of the library. I got something to work and put the code up to the netmf-tiny branch. There are four main classes: Client, Sender, Receiver and Message. The client internally manages one connection and one session. It supports two links for Sender and Receiver (maybe at different addresses) respectively. The PE file size is reduced to 24KB (from 62KB). The new sample (Device.SmallMemory) shows how to use it. There are a few things remaining (e.g. error handling, code cleanup, etc) but it should be working in most cases. Feedback is very welcome.

Regards,
Xin

Regards,
Xin

**Comment by josesimoes** [comment]
Hi,
I've been rather busy with other projects so I had no time to play around with the new branch. I've briefly looked at the code and it sure looks tiny! :smile: 
Quite promising indeed.

**Comment by josesimoes** [comment]
Hi Xin,

I've been working on this. Had to struggle with a couple of details in the code but finally got it working. It has been validated with Azure IoT Hub.
Please take a look at the PRs that I've sent. The commit message and the code changes are pretty much self explanatory (I think... :smile:).
Also changed the sample program to work with Azure IoT Hub.

Question: do you plan to add this to the "official" release with a nuget package and all? I'm asking because I've been working on implementing the NETMF port for the IoT SDK. The AMQP part is waiting for this code. If you plan to release a nuget package I'll reference it, if not, I'll just go ahead and reuse the code there.

**Comment by josesimoes** [comment]
@xinchen10  I'm copying here your "wish list" from PR #55.
Trust the 1 and 3 are OK. Any suggestions on 2 and 4?

~~1. connection idle timeout: need a heartbeat timer to connect reliably to Azure.~~

2. multiple senders/receivers: I think we can support up to 4 or 8 senders/receivers from a single client without introducing significant overhead in space/memory. This might be useful for security token authentication and other request/response communication.

~~3. error codes: the codes in AssertAndThrow should be all unique and grouped by file. Right now I just put random numbers there.~~

4. some type of negative testing to make sure the client does not hang or crash in such conditions.

**Comment by xinchen10** [comment]
@josesimoes I added support for up to 8 senders or receivers on a Client object, and made some updates to traces and idle-time-out handling.

**Comment by josesimoes** [comment]
@xinchen10 excelent! Looks good.
I've updated the list above.
Still not sure about 4.... Should this go into the unit test project or you are suggesting to add "sanity checks" in the code?

**Comment by josesimoes** [comment]
@xinchen10 I'm also thinking that the Client should implement event handlers to let the caller app know when a connection is established and closed (as a minimum).

**Comment by josesimoes** [comment]
@xinchen10 Let me ask you this again: do you plan to release an official nuget package with the "Tiny" version?

**Comment by xinchen10** [comment]
@josesimoes yes that's the plan. But I don't know what's the best way to release it. If it is included in the same (current) package, will it cause confusion to the NuGet client when resolving references?

**Comment by josesimoes** [comment]
@xinchen10 I believe I can help you with that. In a Nuget package you can only target different platforms, not provide different versions for the same platfor

**Comment by xinchen10** [comment]
@josesimoes I merged netmf-tiny into master. Do you think this PR is still needed?

**Comment by josesimoes** [comment]
@xinchen10 awesome. I believe it can be closed now. Being in the master branch any further changes that are required should have a new PR. Nice helping you on this. 
When do you plan to release the office Nuget Package?

**Pull request closed without merging**
