### PR TITLE
Improvements in netmf tiny

### PR DESCRIPTION
**Pull request by josesimoes**
- add properties class to message
- add trace details to help debugging
- add out window to Begin performative
- minor corrections in OnFrame code
- add initial values to several client properties
- update sample program to connect to Azure IoT Hub

### CODE REVIEW

**Comment by xinchen10** [comment]
I applied the changes to the netmf-tiny branch except that I didn't include Properties.cs. The message Properties is exposed as a list on Message directly. Added getter/setter for most commonly used ones. If one needs access to other fields, they can get the List and access the object by index. I think the session window update on receiving Begin may not be right so I updated it.

There are a few more things needed to make the code usable. I am keep it in the netmf-tiny branch.

Thanks.
Xin

**Comment by josesimoes** [comment]
@xinchen10 - understood, it makes sense and it definitely helps achieving the TINY goal.
What other changes you find necessary to make it "usable"? Can I help with that?

**Comment by josesimoes** [comment]
@xinchen10: noticed that you've removed the empty line at the end of the files. I put there because GitHub diff tool and scripts seems to require that in order to behave nicely.

**Comment by xinchen10** [comment]
@josesimoes I applied the changes manually and didn't realize the empty line is needed. The following is a list of things I'd like to do:
1. connection idle timeout: need a heartbeat timer to connect reliably to Azure.
2. multiple senders/receivers: I think we can support up to 4 or 8 senders/receivers from a single client without introducing significant overhead in space/memory. This might be useful for security token authentication and other request/response communication.
3. error codes: the codes in AssertAndThrow should be all unique and grouped by file. Right now I just put random numbers there.
4. some type of negative testing to make sure the client does not hang or crash in such conditions.

**Pull request closed without merging**
